Fix passbolt restore template

diff --git a/templates/passbolt-restore.sh.j2 b/templates/passbolt-restore.sh.j2
--- a/templates/passbolt-restore.sh.j2
+++ b/templates/passbolt-restore.sh.j2
@@ -2,56 +2,93 @@
 
 #{{ ansible_managed }}
 
-unset -v latest_backup
-unset -v rst_option
-unset -v rst_origin
-unset -v origin_file
+function perform_restore(){
 
-echo -e "Are you sure you want to restore? Yes/No";
-read rst_option;
+    # find latest backup file
+    echo "Restoring $rst_origin server. Finding latest $origin_file.tgz file..."
 
-if [ $rst_option == 'Yes' ];
-  then
+    for file in $(find {{ backup_path }} -type f -name *$origin_file.tgz)
+    do
+        [[ $file -nt $latest_backup ]] && latest_backup=$file
+    done
+
+    if [[ -n "$latest_backup" ]]; then
+
+        echo -e "Using $latest_backup file"
+
+        # stop services
+        systemctl stop nginx
+
+        # restore file backup
+        tar xvzf $latest_backup -C /
+
+        # restore database backup
+        mysqldump=$(tar tzf $latest_backup | grep mysqldump)
+        mysql < /$mysqldump
+
+        sudo su -s /bin/bash -c "{{ passbolt_bin_path }}/cake passbolt cleanup" {{ passbolt_user }}
+
+        # start services
+        systemctl start nginx
+        sudo su -s /bin/bash -c "{{ passbolt_bin_path }}/cake passbolt healthcheck" {{ passbolt_user }}
+    else
+        echo -e "File not found"
+    fi
+}
+
+function verify_restore_server(){
+
+    shopt -s nocasematch
+
+    if [[ "^master$" =~ $rst_origin ]]; then
+
+        origin_file=passbolt-{{ passbolt_master }};
+
+    elif [[ "^slave$" =~ $rst_origin ]]; then
+
+        origin_file=passbolt-{{ _passbolt_slave }};
+
+    fi
+
+    shopt -u nocasematch
+
+    if [[ -n "$origin_file" ]]; then
+        perform_restore
+    else
+        echo -e "Enter either master or slave to restore..."
+    fi
+}
+
+function confirm_restore() {
+
+    unset -v latest_backup
+    unset -v rst_option
+    unset -v rst_origin
+    unset -v origin_file
+
     echo -e "Do you want to restore with Master or Slave database? Master/Slave";
     read rst_origin;
 
-    if [ $rst_origin == 'Master' ];
-      then
-        origin_file={{ backup_identifier }};
-    elif [ $rst_origin == 'Slave' ];
-      then
-        origin_file=passbolt-{{ _passbolt_slave }};
-    fi
+    verify_restore_server
+}
 
-    if [ -n '$origin_file' ];
-      then
+function restore_server(){
 
-        # find latest backup file
-        for file in $(find {{ backup_path }} -type f -name *$origin_file.tgz)
-        do
-          [[ $file -nt $latest_backup ]] && latest_backup=$file
-        done
-        if [ -n '$lastest_backup' ]
-          then
-            echo -e "Using $latest_backup file"
+    unset -v latest_backup
+    unset -v rst_option
+    unset -v rst_origin
+    unset -v origin_file
 
-            # stop services
-            systemctl stop nginx
+    rst_origin=$1
 
-            # restore file backup
-            tar xvzf $latest_backup -C /
+    verify_restore_server
+}
 
-            # restore database backup
-            mysqldump=$(tar tzf $latest_backup | grep mysqldump)
-            mysql < /$mysqldump
-
-            sudo su -s /bin/bash -c "{{ passbolt_bin_path }}/cake passbolt cleanup" {{ passbolt_user }}
-
-            # start services
-            systemctl start nginx
-            sudo su -s /bin/bash -c "{{ passbolt_bin_path }}/cake passbolt healthcheck" {{ passbolt_user }}
-          else
-            echo -e "File not found"
-        fi
-    fi
+if [[ $# -eq 0 ]]; then
+    confirm_restore
+elif [[ $# -eq 1 ]]; then
+    restore_server $1
+else
+    echo "Just one passbolt restore server at a time... Exiting"
+    exit 1
 fi
